### ISSUE TITLE
Jupyter not found

### ISSUE THREAD

**Issue by fmarletaz** [kysely/jupyter-notebook-launcher#1]
Hi - I wanted to try Jupyter notebook launcher as it looked promising to me, however, when I downloaded and started it, it doesn't manage to find Jupyter. I have Jupyter installed through CONDA (it is in `/Users/fmarletaz/miniconda2/bin/jupyter`). Can I specify the path somewhere? I am running 10.13.3.

**Comment by trbtm** [comment]
I had the same problem and created a [pull request](https://github.com/kysely/jupyter-notebook-launcher/pull/2), that solved the issue for me.
